import json
from pathlib import Path
cells = []
def md(text):
    cells.append({"cell_type":"markdown","metadata":{},"source":text.splitlines(keepends=True)})
def code(text):
    cells.append({"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":text.splitlines(keepends=True)})
md("# Customer Churn Prediction using Data Analytics and AI\n\n**IBM SkillsBuild Academic Internship | Big Data & Business Management / Data Analytics**\n\nThis notebook looks at customer churn in a telecom-style dataset, checks a few patterns, and compares three starter classifiers. The data currently in `data/raw` is a synthetic teaching copy with the same columns as IBM's public sample because I could not retrieve the original CSV in this workspace. It should not be described as real company data.\n")
md("## 1. Imports and load data\n\nI'm keeping the original CSV under `data/raw` and writing a cleaned copy separately so I can always go back to the first version. Run the notebook from the project root.")
code("from pathlib import Path\nimport sys\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nROOT = Path.cwd()\nif not (ROOT / 'src').exists():\n    ROOT = ROOT.parent\nsys.path.insert(0, str(ROOT / 'src'))\nfrom modeling import prepare_customer_data, train_models, FEATURES\n\nraw_path = ROOT / 'data' / 'raw' / 'Telco-Customer-Churn.csv'\nraw_df = pd.read_csv(raw_path)\nprint('Rows and columns:', raw_df.shape)\nraw_df.head()")
md("## 2. A quick look at the data quality\n\n`TotalCharges` has blanks for brand-new accounts in the source-style format. For those rows, I use zero because there has not been time to accumulate a billed total. I also check for repeated rows and convert the charge columns to numeric before plotting.")
code("print(raw_df.dtypes)\nprint('Duplicate rows:', raw_df.duplicated().sum())\nprint('Blank total charges:', raw_df['TotalCharges'].astype(str).str.strip().eq('').sum())\n\nchurn_df = prepare_customer_data(raw_df)\nclean_path = ROOT / 'data' / 'cleaned' / 'telco_churn_cleaned.csv'\nclean_path.parent.mkdir(parents=True, exist_ok=True)\nchurn_df.to_csv(clean_path, index=False)\nprint('Cleaned shape:', churn_df.shape)\nprint('Churn rate:', round((churn_df['Churn'] == 'Yes').mean() * 100, 1), '%')\nchurn_df[['tenure', 'MonthlyCharges', 'TotalCharges', 'avg_monthly_spend', 'service_count']].describe()")
md("## 3. Exploratory analysis\n\nThese are group-level rates. They help me decide which questions to investigate, but they do not show that any one customer attribute causes churn.")
code("sns.set_theme(style='whitegrid', palette='deep')\n")
plots = [
("Contract type", "Contract", "Month-to-month customers stand out as the group with the highest churn in this sample. Longer contracts may be a useful retention discussion, though a contract choice alone doesn't explain every departure."),
("Tenure", "tenure_bucket", "The churn rate is higher among newer accounts. That points to the first few months as a practical time to improve onboarding and check for early service issues."),
("Monthly charges", "MonthlyCharges", "Customers who leave tend to have a somewhat higher monthly bill here. Price could be part of the story, but it may also reflect which services they use."),
("Internet service", "InternetService", "The internet service groups do not have the same churn rate. I'd look more closely at fiber customers' support experience and bills before drawing conclusions."),
("Payment method", "PaymentMethod", "Electronic check users appear to leave more often in this sample. A payment method might be a signal of customer habits or friction, rather than a reason by itself."),
("Senior citizen", "SeniorCitizen", "The senior-citizen group has a different churn rate, though this binary flag is a rough demographic category and should not be used to stereotype customers."),
("Online security", "OnlineSecurity", "Customers without online security show more churn in this sample. It could be a marker for service mix, so I'd treat it as a lead for a service review."),
("Tech support", "TechSupport", "No tech support is associated with higher churn in the group comparison. Proactive help might be worth offering to customers who have unresolved issues.")]
for idx, (title, col, takeaway) in enumerate(plots, 1):
    md(f"### Chart {idx}: {title}\n\n**What I notice:** {takeaway}")
    if col == 'MonthlyCharges':
        code("fig, ax = plt.subplots(figsize=(7, 4))\nsns.boxplot(data=churn_df, x='Churn', y='MonthlyCharges', ax=ax)\nax.set_title('Monthly charges by churn outcome')\nplt.tight_layout()\nplt.show()")
    elif col == 'tenure_bucket':
        code("plot_data = churn_df.groupby('tenure_bucket', observed=True)['Churn'].apply(lambda s: (s == 'Yes').mean()).reset_index(name='churn_rate')\nfig, ax = plt.subplots(figsize=(7, 4))\nsns.barplot(data=plot_data, x='tenure_bucket', y='churn_rate', color='#6286a5', ax=ax)\nax.set(title='Churn rate by tenure group', xlabel='Tenure', ylabel='Churn rate')\nplt.tight_layout()\nplt.show()")
    else:
        code(f"plot_data = churn_df.groupby('{col}', observed=True)['Churn'].apply(lambda s: (s == 'Yes').mean()).sort_values(ascending=False).reset_index(name='churn_rate')\nfig, ax = plt.subplots(figsize=(8, 4))\nsns.barplot(data=plot_data, x='{col}', y='churn_rate', color='#6286a5', ax=ax)\nax.set(title='Churn rate by {title.lower()}', xlabel='', ylabel='Churn rate')\nax.tick_params(axis='x', rotation=20)\nplt.tight_layout()\nplt.show()")
md("## 4. Feature engineering notes\n\nI grouped tenure into four readable ranges because exact month values make the charts noisy. `service_count` counts services marked Yes, while `avg_monthly_spend` is total charges divided by tenure (and monthly charges for a brand-new account). These are small summaries that may help a model find broader patterns.")
code("churn_df[['tenure', 'tenure_bucket', 'service_count', 'TotalCharges', 'avg_monthly_spend']].head(10)")
md("## 5. Model comparison\n\nThe preprocessing and training live in `src/modeling.py` so the dashboard can use exactly the same transformations. I use a stratified holdout set. The model is selected by ROC-AUC, while precision/recall make the false-alarm versus missed-churn tradeoff more visible.")
code("data, results, selected_model, best_name, X_test, y_test = train_models()\nmetrics = pd.DataFrame(results).T\nmetrics[['accuracy', 'precision', 'recall', 'f1', 'roc_auc']].sort_values('roc_auc', ascending=False)")
code("from sklearn.metrics import ConfusionMatrixDisplay\nfig, axes = plt.subplots(1, 3, figsize=(12, 3.5))\nfor ax, (name, model_info) in zip(axes, results.items()):\n    # The saved metrics include counts in the order: actual no/yes by predicted no/yes.\n    ConfusionMatrixDisplay(np.array(model_info['confusion_matrix']), display_labels=['Stayed', 'Churned']).plot(ax=ax, colorbar=False)\n    ax.set_title(name)\nplt.tight_layout()\nplt.show()\nprint('Selected model:', best_name)")
md("## 6. Business recommendations\n\n1. Test a small retention offer for month-to-month customers before renewal, and measure whether the offer actually reduces churn.\n2. Add a friendly check-in during the first three months, especially after installation or a support contact.\n3. Review fiber customers' bills and support complaints together; the chart alone cannot tell whether price, service quality, or both are involved.\n4. Make automatic payment setup easier, but keep mailed and electronic options available. The payment pattern may be a proxy rather than a cause.\n5. Offer practical security and tech-support guidance when customers sign up, then track take-up and subsequent churn.\n\nThese are tests to run with customers, not guaranteed fixes. The dataset is synthetic, which limits how much can be claimed.")
md("## 7. Limitations and next steps\n\nThis dataset is synthetic and uses deliberately designed patterns, so the model scores are only a workflow demonstration. In a real study, I would get permission to use a real customer dataset, check for leakage and fairness issues, tune the probability threshold based on retention-team capacity, and estimate the cost of false positives and missed churn. I also haven't tested whether the model stays accurate over time.")
notebook = {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python", "version": "3.12.0"}}, "nbformat": 4, "nbformat_minor": 5}
out = Path(__file__).resolve().parents[1] / 'notebooks' / '01_customer_churn_analysis.ipynb'
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(notebook, indent=1), encoding='utf-8')
print('Notebook written with', len(cells), 'cells')
